import type { StreamsAIScope } from '../../auth';
import { createStreamsAIServiceClient, streamsAISchema } from '../../server';
import type { OperationFailure, OperationStage, ProductIntent, RuntimeArtifact, RuntimeOperation } from './contracts';
import { assertTransition, statusForStage, TERMINAL_STAGES } from './state-machine';
const TABLE='streams_ai_operations';
function db(){return streamsAISchema(createStreamsAIServiceClient());}
function map(row:any):RuntimeOperation & {retryCount:number;retryBudget:number;heartbeatAt?:string|null;leaseOwner?:string|null;leaseExpiresAt?:string|null}{return {operationId:row.id,sessionId:row.session_id,turnId:row.turn_id,intent:row.intent,stage:row.stage,status:row.status,idempotencyKey:row.idempotency_key,parentOperationId:row.parent_operation_id,projectId:row.project_id,previewId:row.preview_id,previewUrl:row.preview_url,artifacts:Array.isArray(row.artifacts)?row.artifacts:[],failure:row.failure||null,metadata:row.metadata||{},retryCount:Number(row.retry_count||0),retryBudget:Number(row.retry_budget||2),heartbeatAt:row.heartbeat_at,leaseOwner:row.lease_owner,leaseExpiresAt:row.lease_expires_at};}
export class StreamsOperationRepository {
 async get(scope:StreamsAIScope,id:string){const {data,error}=await db().from(TABLE).select('*').eq('tenant_id',scope.tenantId).eq('user_id',scope.userId).eq('id',id).maybeSingle();if(error)throw new Error(`OPERATION_READ_FAILED:${error.message}`);return data?map(data):null;}
 async findByIdempotency(scope:StreamsAIScope,key:string){const {data,error}=await db().from(TABLE).select('*').eq('tenant_id',scope.tenantId).eq('user_id',scope.userId).eq('idempotency_key',key).maybeSingle();if(error)throw new Error(`OPERATION_READ_FAILED:${error.message}`);return data?map(data):null;}
 async latest(scope:StreamsAIScope,sessionId:string){const {data,error}=await db().from(TABLE).select('*').eq('tenant_id',scope.tenantId).eq('user_id',scope.userId).eq('session_id',sessionId).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(`OPERATION_READ_FAILED:${error.message}`);return data?map(data):null;}
 async create(scope:StreamsAIScope,input:{sessionId:string;turnId:string;intent:ProductIntent;idempotencyKey:string;parentOperationId?:string|null;projectId?:string|null;metadata?:Record<string,unknown>;retryCount?:number;retryBudget?:number}){const existing=await this.findByIdempotency(scope,input.idempotencyKey);if(existing)return existing;const {data,error}=await db().from(TABLE).insert({tenant_id:scope.tenantId,user_id:scope.userId,session_id:input.sessionId,turn_id:input.turnId,intent:input.intent,stage:'RECEIVED',status:'queued',idempotency_key:input.idempotencyKey,parent_operation_id:input.parentOperationId||null,project_id:input.projectId||null,artifacts:[],metadata:input.metadata||{},retry_count:input.retryCount||0,retry_budget:input.retryBudget||2,heartbeat_at:new Date().toISOString()}).select('*').single();if(error)throw new Error(`OPERATION_CREATE_FAILED:${error.message}`);await this.event(scope,data.id,'operation.created','RECEIVED',{intent:input.intent});return map(data);}
 async event(scope:StreamsAIScope,operationId:string,eventType:string,stage:OperationStage,data:Record<string,unknown>={}){const {error}=await db().from('streams_ai_operation_events').insert({tenant_id:scope.tenantId,user_id:scope.userId,operation_id:operationId,event_type:eventType,stage,data});if(error)throw new Error(`OPERATION_EVENT_WRITE_FAILED:${error.message}`);}
 async transition(scope:StreamsAIScope,operationId:string,stage:OperationStage,patch:{status?:RuntimeOperation['status'];projectId?:string|null;previewId?:string|null;previewUrl?:string|null;artifacts?:RuntimeArtifact[];failure?:OperationFailure|null;metadata?:Record<string,unknown>;retryCount?:number}={}){const current=await this.get(scope,operationId);if(!current)throw new Error('OPERATION_NOT_FOUND');if(TERMINAL_STAGES.has(current.stage)&&current.stage!==stage)return current;assertTransition(current.stage,stage);const update:any={stage,status:patch.status||statusForStage(stage),updated_at:new Date().toISOString(),heartbeat_at:new Date().toISOString()};if('projectId'in patch)update.project_id=patch.projectId;if('previewId'in patch)update.preview_id=patch.previewId;if('previewUrl'in patch)update.preview_url=patch.previewUrl;if(patch.artifacts)update.artifacts=patch.artifacts;if('failure'in patch)update.failure=patch.failure;if(patch.metadata)update.metadata={...(current.metadata||{}),...patch.metadata};if(typeof patch.retryCount==='number')update.retry_count=patch.retryCount;const {data,error}=await db().from(TABLE).update(update).eq('tenant_id',scope.tenantId).eq('user_id',scope.userId).eq('id',operationId).eq('stage',current.stage).select('*').single();if(error)throw new Error(`OPERATION_TRANSITION_FAILED:${error.message}`);await this.event(scope,operationId,`operation.${stage.toLowerCase()}`,stage,{status:update.status,previewId:patch.previewId||null,previewUrl:patch.previewUrl||null,failure:patch.failure||null});return map(data);}
 async heartbeat(scope:StreamsAIScope,operationId:string,owner:string){const now=new Date();const expires=new Date(now.getTime()+45_000).toISOString();const {error}=await db().from(TABLE).update({heartbeat_at:now.toISOString(),lease_owner:owner,lease_expires_at:expires}).eq('tenant_id',scope.tenantId).eq('user_id',scope.userId).eq('id',operationId).in('status',['queued','running']);if(error)throw new Error(`OPERATION_HEARTBEAT_FAILED:${error.message}`);}
 async snapshot(scope:StreamsAIScope,operationId:string,stage:OperationStage,artifacts:RuntimeArtifact[],metadata:Record<string,unknown>={}){const {data,error}=await db().from('streams_ai_operation_snapshots').insert({tenant_id:scope.tenantId,user_id:scope.userId,operation_id:operationId,stage,artifacts,metadata}).select('*').single();if(error)throw new Error(`OPERATION_SNAPSHOT_FAILED:${error.message}`);return data;}
}
