export const SAFE_STREAMS_STATUS_PATTERNS = [
  /^Ready$/,
  /^Ask anything$/,
  /^Chat is ready$/,
  /^Adding files…$/,
  /^Dropping files…$/,
  /^Drop files to attach$/,
  /^Pasting image…$/,
  /^Preparing message…$/,
  /^Sending…$/,
  /^Checking file limits…$/,
  /^File limit reached$/,
  /^File is too large$/,
  /^Image is too large$/,
  /^Image dimensions are too large$/,
  /^Spreadsheet is too large$/,
  /^Document token limit reached$/,
  /^Upload limit reached$/,
  /^Storage limit reached$/,
  /^Unsupported file type$/,
  /^Some files could not be added$/,
  /^Uploading…$/,
  /^Uploading 1 file…$/,
  /^Uploading \d+ files…$/,
  /^Upload complete$/,
  /^Upload failed$/,
  /^Retry upload$/,
  /^Processing file…$/,
  /^Extracting text…$/,
  /^Reading PDF…$/,
  /^Reading document…$/,
  /^Reading spreadsheet…$/,
  /^Reading presentation…$/,
  /^Reading code…$/,
  /^Reading attached file…$/,
  /^Reading \d+ attached files…$/,
  /^Reviewing uploaded files…$/,
  /^Files ready$/,
  /^File ready$/,
  /^Text extracted$/,
  /^Extraction complete$/,
  /^No readable text found$/,
  /^Stored as reference$/,
  /^Still processing$/,
  /^Could not extract this file$/,
  /^Inspecting \d+ images?…$/,
  /^Inspecting image…$/,
  /^Preparing image for review…$/,
  /^Checking the reference image…$/,
  /^Using uploaded image as reference…$/,
  /^Image ready for review$/,
  /^Vision unavailable for this image$/,
  /^Looking for text in the image…$/,
  /^No visible text found$/,
  /^Checking PDF pages…$/,
  /^PDF text extracted$/,
  /^Reading DOCX…$/,
  /^Reading CSV…$/,
  /^Reading workbook…$/,
  /^Reading sheet: .+$/,
  /^Workbook extracted$/,
  /^Slides extracted$/,
  /^Reading EPUB…$/,
  /^Reading ODT…$/,
  /^Reading HTML…$/,
  /^Audio uploaded$/,
  /^Transcript pending$/,
  /^Transcribing audio…$/,
  /^Transcript ready$/,
  /^Video uploaded$/,
  /^Sampling frames…$/,
  /^Frames ready$/,
  /^Video analysis unavailable$/,
  /^Thinking…$/,
  /^Understanding your request…$/,
  /^Reviewing your request…$/,
  /^Restoring relevant context…$/,
  /^Checking project context…$/,
  /^Checking conversation context…$/,
  /^Checking available tools…$/,
  /^Choosing the right Streams capability…$/,
  /^Preparing response…$/,
  /^Writing…$/,
  /^Thought for \d+(?:\.\d+)?(?:ms|s)$/,
  /^Thinking longer…$/,
  /^Working through this…$/,
  /^Planning…$/,
  /^Using tool…$/,
  /^Calling app…$/,
  /^Waiting for app response…$/,
  /^Received app response$/,
  /^Received \d+ app responses$/,
  /^Reading app response…$/,
  /^Tool failed$/,
  /^Retrying tool…$/,
  /^Resuming answer…$/,
  /^Searching the web…$/,
  /^Searching sources…$/,
  /^Opening source…$/,
  /^Reading source…$/,
  /^Reviewing sources…$/,
  /^Checking citations…$/,
  /^Search complete$/,
  /^Search failed$/,
  /^Analyzing attached file…$/,
  /^Summarizing document…$/,
  /^Comparing documents…$/,
  /^Extracting key points…$/,
  /^Applying framework…$/,
  /^Transforming document…$/,
  /^Saving to project…$/,
  /^Project file saved$/,
  /^Saving project instructions…$/,
  /^Project instructions saved$/,
  /^Loading project files…$/,
  /^Project context loaded$/,
  /^Moving chat to project…$/,
  /^Chat moved to project$/,
  /^Restoring context…$/,
  /^Context ready$/,
  /^Context compacted$/,
  /^Memory saved$/,
  /^Preparing image request…$/,
  /^Preparing image prompt…$/,
  /^Checking image request…$/,
  /^Checking access…$/,
  /^Starting image generation…$/,
  /^Generating image…$/,
  /^Receiving preview…$/,
  /^Saving image…$/,
  /^Image ready$/,
  /^Preparing video request…$/,
  /^Starting video generation…$/,
  /^Rendering video…$/,
  /^Saving video…$/,
  /^Video ready$/,
  /^Generation failed$/,
  /^Image failed$/,
  /^Video failed$/,
  /^Planning build…$/,
  /^Reading repository…$/,
  /^Reading file…$/,
  /^Applying patch…$/,
  /^Running checks…$/,
  /^Verifying result…$/,
  /^Connecting account…$/,
  /^Account connected$/,
  /^Permission required$/,
  /^Approval required$/,
  /^Fetching data…$/,
  /^Received data$/,
  /^Syncing…$/,
  /^Sync complete$/,
  /^Something went wrong$/,
  /^Invalid image$/,
  /^File unavailable$/,
  /^File still processing$/,
  /^Please try again$/,
  /^Retrying…$/,
  /^Connection lost$/,
  /^Reconnecting…$/,
  /^Request cancelled$/,
  /^Stopping…$/,
  /^Stopped$/,
  /^Checking \d+ attachments?…$/,
  /^Reading \d+ extracted files?…$/,
];

export function normalizeStatusText(value = "") {
  return String(value || "").trim();
}

export function canShowStreamsStatus(value = "") {
  const text = normalizeStatusText(value);
  if (!text) return false;
  return SAFE_STREAMS_STATUS_PATTERNS.some((pattern) => pattern.test(text));
}

export function isVisibleSafeStatus(activity = {}, isStreaming = false) {
  const text = normalizeStatusText(activity?.statusText);
  if (!canShowStreamsStatus(text)) return false;
  if (["Ready", "Ask anything", "Chat is ready"].includes(text)) return false;
  if (isStreaming) return true;
  return /(?:failed|ready|complete|extracted|saved|loaded|connected|cancelled|stopped)$/i.test(text) || text.startsWith("Thought for ") || text.startsWith("Received ") || ["Upload failed", "File ready", "Files ready"].includes(text);
}
