export const SAFE_STREAMS_STATUS_PATTERNS = [
  /^Ready$/,
  /^Ask anything$/,
  /^Chat is ready$/,
  /^Adding files…$/,
  /^Dropping files…$/,
  /^Drop files to attach$/,
  /^Pasting image…$/,
  /^Preparing message…$/,
  /^Sending…$/,
  /^Checking file limits…$/,
  /^File limit reached$/,
  /^File is too large$/,
  /^Image is too large$/,
  /^Image dimensions are too large$/,
  /^Spreadsheet is too large$/,
  /^Document token limit reached$/,
  /^Upload limit reached$/,
  /^Storage limit reached$/,
  /^Unsupported file type$/,
  /^Some files could not be added$/,
  /^Uploading…$/,
  /^Uploading 1 file…$/,
  /^Uploading \d+ files…$/,
  /^Upload complete$/,
  /^Upload failed$/,
  /^Retry upload$/,
  /^Processing file…$/,
  /^Extracting text…$/,
  /^Reading PDF…$/,
  /^Reading document…$/,
  /^Reading spreadsheet…$/,
  /^Reading presentation…$/,
  /^Reading code…$/,
  /^Reading attached file…$/,
  /^Reading \d+ attached files…$/,
  /^Files ready$/,
  /^File ready$/,
  /^Text extracted$/,
  /^Extraction complete$/,
  /^No readable text found$/,
  /^Stored as reference$/,
  /^Still processing$/,
  /^Could not extract this file$/,
  /^Inspecting \d+ images?…$/,
  /^Inspecting image…$/,
  /^Preparing image for review…$/,
  /^Image ready for review$/,
  /^Image URL invalid$/,
  /^Vision unavailable for this image$/,
  /^Looking for text in the image…$/,
  /^No visible text found$/,
  /^Checking PDF pages…$/,
  /^PDF text extracted$/,
  /^PDF under 100 pages$/,
  /^PDF visual review limited$/,
  /^PDF text-only mode$/,
  /^Use PDF viewer page numbers$/,
  /^Reading DOCX…$/,
  /^Legacy DOC stored$/,
  /^Reading CSV…$/,
  /^Reading workbook…$/,
  /^Reading sheet: .+$/,
  /^Workbook extracted$/,
  /^Slides extracted$/,
  /^Reading EPUB…$/,
  /^Reading ODT…$/,
  /^Reading HTML…$/,
  /^Audio uploaded$/,
  /^Transcript pending$/,
  /^Transcribing audio…$/,
  /^Transcript ready$/,
  /^Video uploaded$/,
  /^Sampling frames…$/,
  /^Frames ready$/,
  /^Video analysis unavailable$/,
  /^Thinking…$/,
  /^Thought for \d+(?:\.\d+)?(?:ms|s)$/,
  /^Thinking longer…$/,
  /^Working through this…$/,
  /^Planning…$/,
  /^Using tool…$/,
  /^Calling app…$/,
  /^Waiting for app response…$/,
  /^Received app response$/,
  /^Received \d+ app responses$/,
  /^Reading app response…$/,
  /^Tool failed$/,
  /^Retrying tool…$/,
  /^Tool result too large$/,
  /^Resuming answer…$/,
  /^Searching the web…$/,
  /^Searching sources…$/,
  /^Opening source…$/,
  /^Reading source…$/,
  /^Checking citations…$/,
  /^Search complete$/,
  /^Search failed$/,
  /^Analyzing attached file…$/,
  /^Summarizing document…$/,
  /^Comparing documents…$/,
  /^Extracting key points…$/,
  /^Applying framework…$/,
  /^Transforming document…$/,
  /^Saving to project…$/,
  /^Project file saved$/,
  /^Saving project instructions…$/,
  /^Project instructions saved$/,
  /^Loading project files…$/,
  /^Project context loaded$/,
  /^Moving chat to project…$/,
  /^Chat moved to project$/,
  /^Loading chat history…$/,
  /^Restoring context…$/,
  /^Context ready$/,
  /^Context compacted$/,
  /^Memory saved$/,
  /^Generating image…$/,
  /^Image ready$/,
  /^Rendering video…$/,
  /^Using uploaded image as reference…$/,
  /^Video ready$/,
  /^Generation failed$/,
  /^Image failed$/,
  /^Video failed$/,
  /^Planning build…$/,
  /^Reading repository…$/,
  /^Reading file…$/,
  /^Applying patch…$/,
  /^Connecting account…$/,
  /^Account connected$/,
  /^Permission required$/,
  /^Fetching data…$/,
  /^Received data$/,
  /^Syncing…$/,
  /^Sync complete$/,
  /^Something went wrong$/,
  /^Provider error$/,
  /^Invalid image URL$/,
  /^File unavailable$/,
  /^File still processing$/,
  /^Please try again$/,
  /^Retrying…$/,
  /^Connection lost$/,
  /^Reconnecting…$/,
  /^Request cancelled$/,
  /^Checking \d+ attachments?…$/,
  /^Reading \d+ extracted files?…$/,
];

export function normalizeStatusText(value = "") {
  return String(value || "").trim();
}

export function canShowStreamsStatus(value = "") {
  const text = normalizeStatusText(value);
  if (!text) return false;
  return SAFE_STREAMS_STATUS_PATTERNS.some((pattern) => pattern.test(text));
}

export function isVisibleSafeStatus(activity = {}, isStreaming = false) {
  const text = normalizeStatusText(activity?.statusText);
  if (!canShowStreamsStatus(text)) return false;
  if (text === "Ready" || text === "Ask anything" || text === "Chat is ready") return false;
  if (isStreaming) return true;
  return /(?:failed|ready|complete|extracted|saved|loaded|connected|cancelled)$/i.test(text) || text.startsWith("Thought for ") || text.startsWith("Received ") || text === "Upload failed" || text === "File ready" || text === "Files ready";
}
