export type BuildTaskStatus =
  | "created" | "planning" | "retrieving_context" | "ready_to_patch" | "patching" | "running_checks"
  | "summarizing_errors" | "repairing" | "waiting_for_ci" | "ready_for_review" | "blocked" | "failed" | "completed";
export type Classification = "Proven" | "Implemented but unproven" | "Blocked" | "Rejected";
export type CapabilityState = "real" | "partial" | "blocked" | "missing" | "unknown";
export type BuildDomain = "chat_runtime"|"preview_artifact_workspace"|"image_generation"|"video_generation"|"editor_system"|"person_system"|"upload_reference_ingest"|"github_repo_builder"|"pr_guardrails"|"provider_capabilities"|"ui_design_system"|"persistence_artifacts"|"proof_classification"|"lint_baseline_remediation"|"self_build_runtime"|"unknown";
export type BlockerType = "same_slice_failure"|"unrelated_repo_baseline"|"generated_file_failure"|"scope_policy_failure"|"rule_confirmation_failure"|"ci_build_failure"|"merge_conflict"|"missing_permission"|"missing_runtime_capability"|"workspace_unavailable"|"command_unavailable"|"git_write_unavailable"|"durable_persistence_unavailable"|"browser_proof_unavailable";
export type FailureType = "type_error"|"lint_error"|"build_error"|"scope_guard_failure"|"generated_file_failure"|"audit_failure"|"rule_confirmation_failure"|"merge_conflict"|"package_install_failure"|"command_unavailable"|"workspace_unavailable"|"unrelated_repo_baseline"|"unknown";
export interface CheckResult { name:string; status:"passed"|"failed"|"blocked"|"not_run"; command:string; exitCode:number|null; outputExcerpt:string; durationMs:number; startedAt:string; completedAt:string; blockedReason?:string; }
export interface PatchRecord { id:string; type:"unified_diff"|"replace_file"|"replace_range"|"anchor_patch"|"exact_replace"; targets:string[]; applied:boolean; blockedReason?:string; createdAt:string; }
export interface ErrorSummary { failureType: FailureType; fileLine?: string; rootCause: string; repairConstraints: string[]; rawExcerpt: string; repairAllowedByPolicy: boolean; }
export interface BuildStep { step:string; at:string; status:BuildTaskStatus; }
export interface ProofReport { classification:Classification; changedFiles:string[]; patchesApplied:PatchRecord[]; commandsRun:CheckResult[]; guardResults:CheckResult[]; blockedItems:string[]; proofStillMissing:string[]; generatedFilesRestored:string[]; }
export interface ContextPacket { activeSlice:string; mergePolicyPath?:string; allowedFiles:string[]; forbiddenFiles:string[]; affectedFiles:string[]; proofRequirements:string[]; blockedCapabilities:string[]; guardrailRequirements:string[]; sources:Array<{path:string;kind:"source"|"doc"|"policy"|"state";availability:CapabilityState}>; }
export interface BuildTask { id:string; userId?:string; workspaceId?:string; projectId?:string; title:string; prompt:string; activeSlice:string; domain:BuildDomain; repo?:string; baseBranch:string; taskBranch?:string; status:BuildTaskStatus; phase:BuildTaskStatus; projectProfile:string; mergePolicy?:string; allowedFiles:string[]; forbiddenFiles:string[]; changedFiles:string[]; contextPacket?:ContextPacket; patches:PatchRecord[]; checks:CheckResult[]; commandRuns:CheckResult[]; errors:ErrorSummary[]; repairs:Array<{attempt:number;result:"applied"|"blocked"|"failed"}>; proof?:ProofReport; classification:Classification; blockedReason?:string; createdAt:string; updatedAt:string; parentTaskId?:string; blockedBy:string[]; unblocks:string[]; relatedPr?:string; blockerType?:BlockerType; }
export interface ProjectBuildProfile { id:string; packageManager:"pnpm"|"npm"|"yarn"|"python"|"generic"; commands:Record<string,string>; guardScripts:string[]; generatedFiles:string[]; forbiddenFiles:string[]; mergePolicyRoot:string; }
