import type { ProviderCapability } from "@/lib/streams/quality/quality-governor";

export const STREAMS_IMAGE_PROVIDER_CAPABILITIES: ProviderCapability[] = [
  {
    provider: "fal",
    model: "kontext",
    mediaType: "image",
    supportsExactDimensions: false,
    supportsBulk: true,
    supportsImg2Img: true,
    supportsInpaint: false,
    supportsOutpaint: false,
    supportsUpscale: false,
    supportedAspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    realismTier: 5,
    promptAdherenceTier: 5,
    speedTier: 3,
    costTier: 3,
  },
  {
    provider: "fal",
    model: "kontext-max",
    mediaType: "image",
    supportsExactDimensions: false,
    supportsBulk: true,
    supportsImg2Img: true,
    supportsInpaint: false,
    supportsOutpaint: false,
    supportsUpscale: false,
    supportedAspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    realismTier: 5,
    promptAdherenceTier: 5,
    speedTier: 2,
    costTier: 4,
  },
  {
    provider: "fal",
    model: "flux-pro",
    mediaType: "image",
    supportsExactDimensions: true,
    supportsBulk: true,
    supportsImg2Img: false,
    supportsInpaint: false,
    supportsOutpaint: false,
    supportsUpscale: false,
    supportedAspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    minWidth: 64,
    maxWidth: 2048,
    minHeight: 64,
    maxHeight: 2048,
    realismTier: 5,
    promptAdherenceTier: 4,
    speedTier: 3,
    costTier: 4,
  },
  {
    provider: "fal",
    model: "flux-dev",
    mediaType: "image",
    supportsExactDimensions: true,
    supportsBulk: true,
    supportsImg2Img: false,
    supportsInpaint: false,
    supportsOutpaint: false,
    supportsUpscale: false,
    supportedAspectRatios: [],
    minWidth: 64,
    maxWidth: 1440,
    minHeight: 64,
    maxHeight: 1440,
    realismTier: 4,
    promptAdherenceTier: 4,
    speedTier: 4,
    costTier: 2,
  },
  {
    provider: "fal",
    model: "seedream",
    mediaType: "image",
    supportsExactDimensions: true,
    supportsBulk: true,
    supportsImg2Img: false,
    supportsInpaint: false,
    supportsOutpaint: false,
    supportsUpscale: false,
    supportedAspectRatios: [],
    minWidth: 64,
    maxWidth: 2048,
    minHeight: 64,
    maxHeight: 2048,
    realismTier: 4,
    promptAdherenceTier: 4,
    speedTier: 3,
    costTier: 3,
  },
];

export function normalizeStreamsImageModel(model?: string | null): string {
  return (model || "kontext").toLowerCase().trim().replace(/\s+/g, "-");
}

export function isExactSizeRequest(width?: number, height?: number): boolean {
  return Number.isFinite(width) && Number.isFinite(height) && Number(width) > 0 && Number(height) > 0;
}
