import { isValidElement, memo, useEffect, useMemo, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeSanitize from "rehype-sanitize";
import ChatArtifacts from "./ChatArtifacts";
import { highlightCode } from "./syntaxHighlight";
import "./chat-markdown.css";
import "./artifact-theme.css";
import "./syntax-highlight.css";

const STREAM_PACING={largeDeltaThresholdChars:220,sentenceChunkMaxChars:180,lineChunkMaxChars:160,fallbackChunkMaxChars:120,minimumChunkDelayMs:24,maximumChunkDelayMs:72,millisecondsPerCharacter:.55,autoScrollOnlyWithinPx:220};
const normalizeMarkdownContent=(content)=>String(content||"").replace(/\r\n/g,"\n").replace(/\u00a0/g," ").trimEnd();
function nodeText(node){if(node==null||typeof node==="boolean")return"";if(typeof node==="string"||typeof node==="number")return String(node);if(Array.isArray(node))return node.map(nodeText).join("");if(isValidElement(node))return nodeText(node.props?.children);return"";}
function getSafeHref(href=""){const value=String(href||"").trim();if(!value)return"";if(/^(https?:|mailto:|tel:)/i.test(value))return value;if(value.startsWith("/")||value.startsWith("#"))return value;return"";}
function makeReadableChunks(text=""){const value=String(text||""),pieces=[],pattern=new RegExp(`([^.!?\\n]{1,${STREAM_PACING.sentenceChunkMaxChars}}[.!?]\\s+|[^\\n]{1,${STREAM_PACING.lineChunkMaxChars}}\\n+|\\S.{0,${STREAM_PACING.fallbackChunkMaxChars}}(?:\\s+|$))`,`g`);let match;while((match=pattern.exec(value)))pieces.push(match[0]);return pieces.length?pieces:value.match(new RegExp(`[\\s\\S]{1,${STREAM_PACING.fallbackChunkMaxChars}}`,`g`))||[];}
function scrollStreamingMessage(){if(typeof window==="undefined")return;window.requestAnimationFrame(()=>{const node=[document.querySelector(".operatorChatScroll"),document.querySelector(".startChatSurface"),document.querySelector(".chatScroll"),document.querySelector(".splitChatScroll")].filter(Boolean)[0];if(!node)return;const distance=node.scrollHeight-node.scrollTop-node.clientHeight;if(distance<STREAM_PACING.autoScrollOnlyWithinPx)node.scrollTo({top:node.scrollHeight,behavior:"smooth"});});}
function CopyButton({value}){const[copied,setCopied]=useState(false);const copy=async()=>{try{await navigator?.clipboard?.writeText?.(value);setCopied(true);window.setTimeout(()=>setCopied(false),1200);}catch{setCopied(false);}};return <button type="button" className="chatCodeCopyButton" onClick={copy} aria-label="Copy code block">{copied?"Copied":"Copy"}</button>}
function CodeBlock({inline,className,children}){const raw=String(children||"").replace(/\n$/,"");const match=/language-([a-zA-Z0-9_-]+)/.exec(className||"");const language=match?.[1]||"text";const isBlock=!inline&&(Boolean(match)||raw.includes("\n"));const highlighted=useMemo(()=>highlightCode(raw,language),[raw,language]);if(!isBlock)return <code className="chatInlineCode">{children}</code>;return <figure className="chatCodeBlock" data-language={language}><figcaption className="chatCodeHeader"><span>{language}</span><CopyButton value={raw}/></figcaption><pre className="chatCodePre" tabIndex={0}><code className={className} dangerouslySetInnerHTML={{__html:highlighted}}/></pre></figure>}
function SafeLink({children,href}){const safeHref=getSafeHref(href);if(!safeHref)return <span>{children}</span>;const text=nodeText(children),external=/^https?:/i.test(safeHref),citation=/^(citation:|source:)/i.test(href||"")||/^\[?\d+(?:[-–,]\d+)*\]?$/.test(text.trim()),download=/download/i.test(text)||/\.(zip|pdf|docx|xlsx|csv|pptx)(\?|$)/i.test(safeHref);return <a className={citation?"chatCitationLink":download?"chatDownloadLink":undefined} href={safeHref} target={external?"_blank":undefined} rel={external?"noreferrer noopener":undefined}>{children}</a>}
const SEMANTIC=[[/^success\s*:/i,"success","Success","✓"],[/^warning\s*:/i,"warning","Warning","!"],[/^error\s*:/i,"error","Error","×"],[/^(info|information)\s*:/i,"info","Info","i"],[/^worked\s+for\b/i,"worked","Worked","◷"],[/^(thinking|searching|streaming|generating|using tools)\s*:/i,"process","Process","●"],[/^progress\s*:/i,"progress","Progress","↗"],[/^(status|badge|version|confidence|live)\s*:/i,"badge","Status","◆"]];
function Paragraph({children}){const text=nodeText(children).trim(),entry=SEMANTIC.find(([pattern])=>pattern.test(text));if(entry){const[pattern,type,label,icon]=entry,detail=text.replace(pattern,"").trim(),visible=type==="worked"?text:label;return <div className={`chatInlineArtifact chatInlineArtifact--${type}`} role={type==="error"?"alert":"status"}><span className="chatInlineArtifactIcon" aria-hidden="true">{icon}</span><span className="chatInlineArtifactCopy"><strong>{visible}</strong>{type!=="worked"&&detail?<small>{detail}</small>:null}</span></div>}const className=/^key outcome\s*:/i.test(text)?"chatLeadLine chatLeadLine--outcome":/^implementation priorities\s*:/i.test(text)?"chatLeadLine chatLeadLine--priority":undefined;return <p className={className}>{children}</p>}
function Table({children}){return <div className="chatTableWrap" role="region" aria-label="Scrollable table" tabIndex={0}><table>{children}</table></div>}
function ChatMarkdownMessage({content,message={},runtime}){const fullMarkdown=useMemo(()=>normalizeMarkdownContent(content),[content]);const[displayMarkdown,setDisplayMarkdown]=useState(fullMarkdown);const initializedRef=useRef(false),previousFullRef=useRef(fullMarkdown),timerRef=useRef(null);useEffect(()=>{window.clearTimeout(timerRef.current);if(!initializedRef.current){initializedRef.current=true;previousFullRef.current=fullMarkdown;setDisplayMarkdown(fullMarkdown);return;}const previous=previousFullRef.current||"";previousFullRef.current=fullMarkdown;if(!fullMarkdown.startsWith(previous)){setDisplayMarkdown(fullMarkdown);return;}const delta=fullMarkdown.slice(previous.length);if(!delta)return;if(delta.length<STREAM_PACING.largeDeltaThresholdChars){setDisplayMarkdown(fullMarkdown);scrollStreamingMessage();return;}const chunks=makeReadableChunks(delta);let index=0,current=previous;const step=()=>{const next=chunks[index];if(!next)return;current+=next;index+=1;setDisplayMarkdown(current);scrollStreamingMessage();if(index<chunks.length){const delay=Math.max(STREAM_PACING.minimumChunkDelayMs,Math.min(STREAM_PACING.maximumChunkDelayMs,next.length*STREAM_PACING.millisecondsPerCharacter));timerRef.current=window.setTimeout(step,delay);}};step();return()=>window.clearTimeout(timerRef.current);},[fullMarkdown]);return <div className="chatMessageContent"><div className="chatMarkdown"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]} components={{p:Paragraph,code:CodeBlock,table:Table,a:SafeLink,h1:({children})=><h1>{children}</h1>,h2:({children})=><h2>{children}</h2>,h3:({children})=><h3>{children}</h3>,h4:({children})=><h4>{children}</h4>,h5:({children})=><h5>{children}</h5>,h6:({children})=><h6>{children}</h6>,blockquote:({children})=><blockquote>{children}</blockquote>}}>{displayMarkdown}</ReactMarkdown></div><ChatArtifacts message={{...message,content:content||message.content}} runtime={runtime}/></div>}
export default memo(ChatMarkdownMessage);
