"use client";
import { useMemo,useState } from "react";
const list=v=>Array.isArray(v)?v.filter(Boolean):[];
const bytes=v=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)return"";const u=["B","KB","MB","GB"],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`};
function Status({status="info",title,detail}){return <div className={`chatArtifactStatus chatArtifactStatus--${status}`} role={status==="error"?"alert":"status"}><i aria-hidden="true"/><span><b>{title||status}</b>{detail?<small>{detail}</small>:null}</span></div>}
function Progress({value=0,label="Progress"}){const n=Math.max(0,Math.min(100,Number(value)||0));return <div className="chatArtifactProgress"><div><b>{label}</b><span>{n}%</span></div><progress max="100" value={n}>{n}%</progress></div>}
function Sources({items}){const[open,setOpen]=useState(false);if(!items.length)return null;const shown=open?items:items.slice(0,5);return <section className="chatArtifactSection"><header><h4>Sources</h4><span>{items.length}</span></header><ol>{shown.map((s,i)=><li key={s.id||s.url||i}><b>{i+1}. {s.title||s.name||s.domain||"Source"}</b><small>{[s.publisher,s.domain,s.date].filter(Boolean).join(" · ")}</small>{s.url?<a href={s.url} target="_blank" rel="noreferrer">Open ↗</a>:null}</li>)}</ol>{items.length>5?<button onClick={()=>setOpen(v=>!v)}>{open?"Show fewer":`View all ${items.length} sources`}</button>:null}</section>}
function Files({items,title="Files"}){if(!items.length)return null;return <section className="chatArtifactSection"><header><h4>{title}</h4><span>{items.length}</span></header><ul>{items.map((f,i)=><li key={f.id||i}><b>{f.name||f.title||`File ${i+1}`}</b><small>{[f.kind||f.type,bytes(f.size||f.sizeBytes),f.status].filter(Boolean).join(" · ")}</small>{f.url?<a href={f.url} target="_blank" rel="noreferrer">Open</a>:null}</li>)}</ul></section>}
function Tools({items}){if(!items.length)return null;return <section className="chatArtifactSection"><header><h4>Activity</h4><span>{items.length}</span></header><ol>{items.map((t,i)=><li className={`toolState--${t.status||"complete"}`} key={t.id||i}><b>{t.name||t.tool||"Tool"}</b><small>{t.description||t.statusText||t.status}</small></li>)}</ol></section>}
export default function ChatArtifacts({message={}}){const sources=useMemo(()=>list(message.sources||message.citations),[message]),uploaded=useMemo(()=>list(message.uploadedAssets||message.files),[message]),generated=useMemo(()=>list(message.generatedFiles||message.downloads),[message]),tools=useMemo(()=>list(message.toolCalls||message.tools),[message]);const status=message.status&&!['complete','streaming'].includes(message.status)?message.status:null;return <div className="chatArtifacts">{status?<Status status={status} title={message.statusTitle} detail={message.statusText||message.error}/>:null}{message.progress!=null||message.progressPercent!=null?<Progress value={message.progress??message.progressPercent} label={message.progressLabel}/>:null}<Sources items={sources}/><Files items={uploaded}/><Files items={generated} title="Generated files"/><Tools items={tools}/></div>}
