export const STREAMS_VISIONS_EXPERIENCE_CONTRACT = Object.freeze({
  route: "/streams-ai/Visions",
  messagesApi: "/api/streams-ai/Visions/messages",
  conversationsApi: "/api/streams-ai/Visions/conversations",
  identity: Object.freeze({
    statusApi: "/api/streams-ai/Visions/identity/status",
    challengeApi: "/api/streams-ai/Visions/identity/challenge",
    capturesApi: "/api/streams-ai/Visions/identity/captures",
    biometricApi: "/api/streams-ai/Visions/identity/biometric",
    reviewApi: "/api/streams-ai/Visions/identity/review",
    privateBucket: "streams-visions-likeness",
    profileTable: "streams_visions_identity_profiles",
    assetsTable: "streams_visions_likeness_assets",
    eventsTable: "streams_visions_identity_events",
    requiredCaptures: 4,
    requiresEmailVerification: true,
    requiresPhoneVerification: true,
    requiresAccountDetails: true,
    requiresIdentityNotice: true,
    requiresVerifiedLiveness: true,
    requiresApprovedLikeness: true,
    requiresDeviceLock: true,
    publicAssetUrls: false,
    legalIdentityClaim: false,
  }),
  storage: Object.freeze({
    conversation: "streams-visions.conversation.v1",
    mode: "streams-visions.mode.v1",
  }),
  events: Object.freeze({
    messageStarted: "visions:message-started",
    messageComplete: "visions:message-complete",
    previewRevealing: "visions:preview-revealing",
    previewReady: "visions:preview-ready",
    previewFailed: "visions:preview-failed",
    previewCancelled: "visions:preview-cancelled",
  }),
  persistence: Object.freeze({
    conversationsTable: "streams_visions_conversations",
    messagesTable: "streams_visions_messages",
    activePreviewField: "active_preview",
  }),
  reveal: Object.freeze({
    minimumMs: 4200,
    maximumMs: 8000,
    defaultMs: 5200,
    ambientClass: "ambientDream",
    futureSelfClass: "futureSelf",
    reducedMotionSupported: true,
    visibleGeneratorIndicators: false,
  }),
  isolation: Object.freeze({
    importsCurrentChatRuntime: false,
    usesMainStreamsMessagesApi: false,
    usesMainStreamsAssetCache: false,
  }),
  publicErrors: Object.freeze({
    providerFailure: "Visions could not shape that scene",
    exposesProviderDetails: false,
  }),
});
